# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  name: Default

stages:
- stage: Build
  displayName: Build Docker images
  jobs:
  - job: Build_Backend_Image
    displayName: Build Backend Image
    steps:
    - task: Docker@2
      displayName: Log in to DockerHub
      inputs:
        command: login
        containerRegistry: DockerHub
    - task: Docker@2
      displayName: Build backend image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
        repository: arvindgorur/my-wx-app-be
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Logout of DockerHub
      inputs:
        command: logout
        containerRegistry: DockerHub

  - job: Build_Frontend_Image
    displayName: Build Frontend Image
    steps:
    - task: Docker@2
      displayName: Log in to DockerHub
      inputs:
        command: login
        containerRegistry: DockerHub
    - task: Docker@2
      displayName: Build frontend image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
        repository: arvindgorur/my-wx-app-fe
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Logout of DockerHub
      inputs:
        command: logout
        containerRegistry: DockerHub
