# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker images
  jobs:  
  - job: Build_Backend_Image
    displayName: Build BE
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build backend image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend/Dockerfile'
        tags: |
          $(tag)
  - job: Build_Frontend_Image
    displayName: Build FE
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build frontend image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/frontend/Dockerfile'
        tags: |
          $(tag)
